/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'main'}],
  contractSidebar: [{type: 'autogenerated', dirName: 'contracts'}]
  // {
  //   'Overview': ['contracts/README'],
  //   'Interfaces': {
  //     'IAmmalgamPair': ['contracts/interfaces/IAmmalgamPair.sol/interface.IAmmalgamPair'],
  //     'factories': {
  //       'Overview': ['contracts/interfaces/factories/README'],
  //       'IAmmalgamFactory': ['contracts/interfaces/factories/IAmmalgamFactory.sol/interface.IAmmalgamFactory'],
  //       'IAmmalgamFactoryCallback': ['contracts/interfaces/factories/IAmmalgamFactoryCallback.sol/interface.IAmmalgamFactoryCallback'],
  //       'ITokenFactory': ['contracts/interfaces/factories/ITokenFactory.sol/interface.ITokenFactory'],
  //     },
  //   }
  // },
};

module.exports = sidebars;
